retrieval:
  collection_name: gotmat_collection
  embedding_model: intfloat/multilingual-e5-large
  milvus_host: localhost
  milvus_port: "19530"
  top_k: 5
generation:
  model_path: Helsinki-NLP/opus-mt-it-en
  adapter_path: models/fine_tuned_models/opus-mt-it-en-v1/model
  tokenizer_path: models/fine_tuned_models/opus-mt-it-en-v1/tokenizer
  model_type: seq2seq
  max_length: 128
  device: auto
  max_new_tokens: 50
output:
  output_dir: data/destination