data:
  source: data/source
  texts: data/texts
  cleaned_texts: data/cleaned_texts
  chunks: data/chunks/prefettura_v1.3_chunks
  embeddings_metadata: data/embeddings/prefettura_v1.3_embeddings
  destination: data/results
  embeddings: data/embeddings/main
model:
  model_type: causal
  reranker_model: dlicari/distil-ita-legal-bert #"dlicari/Italian-Legal-BERT"
  model_path: "distilbert/distilgpt2" #"openai-community/gpt2-large" #meta-llama/Meta-Llama-3-8B-Instruct #"dlicari/Italian-Legal-BERT-SC" #facebook/mbart-large-50 #Helsinki-NLP/opus-mt-it-en
  adapter_path: #models/fine_tuned_models/opus-mt-it-en-v1/model
  tokenizer_path: #"dlicari/Italian-Legal-BERT-SC" #"meta-llama/Meta-Llama-3-8B-Instruct" #facebook/mbart-large-50   #models/fine_tuned_models/opus-mt-it-en-v1/tokenizer
  embedding_model: dlicari/distil-ita-legal-bert #"dlicari/Italian-Legal-BERT-SC" #"dlicari/Italian-Legal-BERT"  #intfloat/multilingual-e5-large-instruct 
supported_formats:
  - .text
  - .txt
  - .jpg
  - .jpeg
  - .gif
  - .png
  - .pdf
embedding_dim: 768
collection_name: gotmat_collection
milvus_host: localhost
milvus_port: 19530
max_input_tokenization_length: 512
max_new_tokens: 800
device: auto
max_chunk_words: 500
max_chunk_length: 2000
min_chunk_length: 10
max_augmentation_contexts: 5
max_context_length: 1000
max_parent_length: 2000
tessdata_dir: C:/Program Files/Tesseract-OCR/tessdata